name: Create Tag

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/MenD32/allpaca/allpaca:${{ github.sha }} --push .
