name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

  build:
    name: Build Allpaca
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        platform: [linux/amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          make build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: "dist/allpaca"

  release:
    needs: build
    name: Release
    runs-on: ubuntu-24.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binary
          path: "./" 

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            allpaca
        